name = "backend"
compatibility_date = "2024-08-18"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZjA3N2VkNTYtZDY1Ni00MTBlLWE2ZDEtYTk4Y2U4ZWE3MTM3IiwidGVuYW50X2lkIjoiMGEwYmQwZTJlOGRhNTYwYzY1OTQ2ZWIzYjIyNzE5NzI4OTVhODlmZDAwOTg4MjgxMmI4YmYzNDRmNzkxNDBmMiIsImludGVybmFsX3NlY3JldCI6IjAyMDVkMDM3LWRiY2YtNGE2OS1iNzAyLTYxYzY0NjU3ZGE3MyJ9.EW5yZV9WnlCgjRaFXNpw228y-R1KAONIru1tyMufz3g"
JWT_SECRET = "secret"
